'use client';

import { useState, useEffect, createContext, useContext } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronRight, ChevronLeft, Sparkles } from 'lucide-react';

/* ─────────────────────────────────────────────
   GUIDE STEP DEFINITIONS
   Each dashboard page has its own ordered steps.
   ───────────────────────────────────────────── */
export type GuideStep = {
  title: string;
  description: string;
  highlight?: string; // CSS selector or area name to call attention to
  position?: 'center' | 'bottom-left' | 'bottom-right' | 'top-right';
};

export const GUIDE_STEPS: Record<string, GuideStep[]> = {
  '/dashboard/map': [
    {
      title: 'Welcome to the WASH Digital Twin',
      description: 'You are now inside a live replica of the Kwali water infrastructure network. Each glowing node on this dark map represents a real water terminal deployed across 15 communities.',
      position: 'center',
    },
    {
      title: 'Color = Health',
      description: 'Blue nodes are operational. Amber nodes are degraded — the AI has detected early signs of failure. Red nodes are broken and offline. The system knows this in real-time from IoT sensors.',
      position: 'bottom-left',
    },
    {
      title: 'Click Any Node',
      description: 'Tap on any glowing terminal to see its live sensor feed: flow rate, energy use, water quality, and an AI diagnostic summary. This is the data that powers the Digital Twin.',
      position: 'bottom-right',
    },
    {
      title: 'Overlay Controls',
      description: 'Use the control panel in the top-left to toggle between the IoT Sensor layer (real data) and the Digital Twin Radar (predictive anomaly overlay).',
      position: 'top-right',
    },
    {
      title: 'Next: See the AI in Action',
      description: 'Now navigate to the Intelligence Lab in the sidebar to see what the Generative AI Engine produced when it analyzed the anomalies on this map.',
      position: 'center',
    },
  ],

  '/dashboard/lab': [
    {
      title: 'The AI Intelligence Lab',
      description: 'This is where the Generative AI Engine (Gemini 2.5) outputs its analysis. Every card below was auto-generated by AI after detecting an anomaly in the Digital Twin.',
      position: 'center',
    },
    {
      title: 'Business Models & Sanitation Designs',
      description: 'The AI picks from 8 approved micro-business strategies and tailors a specific proposal to each failing terminal — based on its unique revenue, location, and failure data.',
      position: 'bottom-left',
    },
    {
      title: 'Stakeholder Review',
      description: 'In a real deployment, community representatives and ward chiefs would review and vote on each AI proposal before it is implemented. The Approve / Recalibrate / Reject buttons simulate this governance layer.',
      position: 'bottom-right',
    },
    {
      title: 'Next: Meet the Steward',
      description: 'Navigate to the Steward Network in the sidebar to see the ground-level operator view — the person who physically manages the water terminal every day.',
      position: 'center',
    },
  ],

  '/dashboard/steward': [
    {
      title: 'Steward Telemetry Dashboard',
      description: 'This is what a local community steward sees. They are the human link in the closed loop — trained volunteers who operate and maintain the water terminal.',
      position: 'center',
    },
    {
      title: 'Live IoT Sensors',
      description: 'The left card shows the steward their terminal\'s real-time health: flow rate, energy consumption, and water quality. If the pump status turns red, the steward knows to act immediately.',
      position: 'bottom-left',
    },
    {
      title: 'Revenue & Activity',
      description: 'The right card shows the steward their weekly earnings from water sales. This is the proof that the micro-business model is working — the steward is earning income, not relying on charity.',
      position: 'bottom-right',
    },
    {
      title: 'Next: Director Mode',
      description: 'Navigate to the Simulation Control in the sidebar. This is where you can trigger the entire simulation yourself — seed the data, simulate time, and fire the AI engine.',
      position: 'center',
    },
  ],

  '/dashboard/control': [
    {
      title: 'Your Mission Starts Here',
      description: 'You are now the system operator. Each phase is locked until you complete the one before it. Click the Execute button to run each phase with your own hands.',
      position: 'center',
    },
    {
      title: 'Phase 4: One Click = One AI Call',
      description: 'The AI phase is different. Each click sends exactly ONE terminal to Gemini. You control the pace. Watch the progress bar fill as you process each community.',
      position: 'bottom-left',
    },
    {
      title: 'Then Explore the Results',
      description: 'Once you\'ve processed terminals, navigate to the Activity Map and Intelligence Lab in the sidebar to see what the AI generated. Dismiss this guide and begin.',
      position: 'center',
    },
  ],
};

/* ─────────────────────────────────────────────
   GUIDE CONTEXT (persists dismissed state)
   ───────────────────────────────────────────── */
type GuideContextType = {
  isGuideActive: boolean;
  setGuideActive: (v: boolean) => void;
  dismissedPages: Set<string>;
  dismissPage: (page: string) => void;
};

const GuideContext = createContext<GuideContextType>({
  isGuideActive: true,
  setGuideActive: () => {},
  dismissedPages: new Set(),
  dismissPage: () => {},
});

export function GuideProvider({ children }: { children: React.ReactNode }) {
  const [isGuideActive, setGuideActive] = useState(true);
  const [dismissedPages, setDismissedPages] = useState<Set<string>>(new Set());

  const dismissPage = (page: string) => {
    setDismissedPages(prev => new Set(prev).add(page));
  };

  return (
    <GuideContext.Provider value={{ isGuideActive, setGuideActive, dismissedPages, dismissPage }}>
      {children}
    </GuideContext.Provider>
  );
}

export function useGuide() {
  return useContext(GuideContext);
}

/* ─────────────────────────────────────────────
   GUIDE OVERLAY COMPONENT
   Renders the step-by-step walkthrough on each page
   ───────────────────────────────────────────── */
export function GuideOverlay({ pathname }: { pathname: string }) {
  const { isGuideActive, dismissedPages, dismissPage } = useGuide();
  const [currentStep, setCurrentStep] = useState(0);

  const steps = GUIDE_STEPS[pathname];
  
  // Reset step when navigating to a new page
  useEffect(() => {
    setCurrentStep(0);
  }, [pathname]);

  if (!steps || !isGuideActive || dismissedPages.has(pathname)) return null;

  const step = steps[currentStep];
  if (!step) return null;
  const isLast = currentStep === steps.length - 1;
  const isFirst = currentStep === 0;
  const progress = ((currentStep + 1) / steps.length) * 100;

  const positionClasses: Record<string, string> = {
    'center': 'top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2',
    'bottom-left': 'bottom-8 left-8',
    'bottom-right': 'bottom-8 right-8',
    'top-right': 'top-24 right-8',
  };

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={`${pathname}-${currentStep}`}
        initial={{ opacity: 0, scale: 0.95, y: 10 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95, y: -10 }}
        transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
        className={`fixed z-[9999] ${positionClasses[step.position || 'center']} max-w-md w-full`}
      >
        <div className="bg-slate-950/95 backdrop-blur-xl border border-blue-500/30 rounded-2xl shadow-[0_0_40px_rgba(59,130,246,0.15)] overflow-hidden">
          
          {/* Progress bar */}
          <div className="h-1 bg-slate-800 w-full">
            <motion.div 
              className="h-full bg-gradient-to-r from-blue-500 to-cyan-400"
              initial={{ width: 0 }}
              animate={{ width: `${progress}%` }}
              transition={{ duration: 0.4 }}
            />
          </div>

          <div className="p-6">
            {/* Header */}
            <div className="flex items-start justify-between mb-4">
              <div className="flex items-center space-x-2">
                <Sparkles size={14} className="text-blue-400" />
                <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-blue-400">
                  Guide — Step {currentStep + 1} of {steps.length}
                </span>
              </div>
              <button 
                onClick={() => dismissPage(pathname)}
                className="text-slate-500 hover:text-slate-300 transition-colors p-1"
              >
                <X size={14} />
              </button>
            </div>

            {/* Content */}
            <h3 className="text-lg font-bold text-white tracking-tight mb-2">{step.title}</h3>
            <p className="text-sm text-slate-400 leading-relaxed">{step.description}</p>

            {/* Navigation */}
            <div className="flex items-center justify-between mt-6 pt-4 border-t border-slate-800/50">
              <button
                onClick={() => setCurrentStep(Math.max(0, currentStep - 1))}
                disabled={isFirst}
                className={`flex items-center space-x-1 text-xs font-bold uppercase tracking-widest transition-colors ${isFirst ? 'text-slate-700 cursor-not-allowed' : 'text-slate-400 hover:text-white'}`}
              >
                <ChevronLeft size={14} />
                <span>Back</span>
              </button>
              
              {isLast ? (
                <button
                  onClick={() => dismissPage(pathname)}
                  className="flex items-center space-x-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold uppercase tracking-widest rounded-lg transition-colors shadow-[0_0_15px_rgba(59,130,246,0.3)]"
                >
                  <span>Got it</span>
                </button>
              ) : (
                <button
                  onClick={() => setCurrentStep(currentStep + 1)}
                  className="flex items-center space-x-1 text-xs font-bold uppercase tracking-widest text-blue-400 hover:text-blue-300 transition-colors"
                >
                  <span>Next</span>
                  <ChevronRight size={14} />
                </button>
              )}
            </div>
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
}
